#!/usr/local_rwth/bin/zsh




#SBATCH --job-name=GS_fast502 # The job name.
#SBATCH -c 10                # The number of cpu cores to use.
#SBATCH --time=47:59:00              # The time the job will take to run.
#SBATCH --mem-per-cpu=3200M        # The memory the job will use per cpu core.
#SBATCH --account=rwth0722
#SBATCH --mail-type=NONE
#SBATCH --mail-user=passetti@physik.rwth-aachen.de


#SBATCH --output=/home/yz004406/output/cori
#

### Change to the work directory
cd /home/yz004406/DMRG/MF/Data_complete_MF
### Execute your application

MKL_NUM_THREADS = 10
export MKL_NUM_THREADS


module load pythoni/3.7
export PYTHONPATH=/home/yz004406/TeNPy
MKL_NUM_THREADS = 10
export MKL_NUM_THREADS


python3 mf.py 2 50


echo $?

date

