#!/usr/local_rwth/bin/zsh




#SBATCH --job-name=GS_fast1100.3 # The job name.
#SBATCH -c 4                # The number of cpu cores to use.
#SBATCH --time=23:59:00              # The time the job will take to run.
#SBATCH --mem-per-cpu=3200M        # The memory the job will use per cpu core.
###SBATCH --account=rwth0926
#SBATCH --account=theophysc
#SBATCH --mail-type=NONE
#SBATCH --mail-user=passetti@physik.rwth-aachen.de


#SBATCH --output=/home/yz004406/output/cori
#

### Change to the work directory
cd /home/yz004406/DMRG/MF
### Execute your application

MKL_NUM_THREADS = 6
export MKL_NUM_THREADS


module load pythoni/3.7
export PYTHONPATH=/home/yz004406/TeNPy
MKL_NUM_THREADS = 6
export MKL_NUM_THREADS


python3 mf_complete.py 1 110 600 3 0.3


echo $?

date

